- name: SSH Remote Commands
  uses: appleboy/ssh-action@v0.0.6
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    port: ${{ secrets.PORT }}
    script: ~/deploy_sciviscourse
